/**
 * Mock roof-measurement report generator.
 *
 * Produces genuine, valid PDF documents (via pdf-lib) so the local/demo flow
 * behaves like production: the homeowner and contractors receive real files they
 * can open. Measurements are derived deterministically from the address so the
 * same property always yields the same numbers.
 */
import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib"

export interface ReportMeta {
  reportId: string
  address: string
  postalCode: string
  product?: string
  color?: string
}

/** Deterministic pseudo-random number in [0,1) seeded by a string. */
function seededRandom(seed: string): () => number {
  let h = 2166136261
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return () => {
    h += 0x6d2b79f5
    let t = h
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/** Roof measurements derived from the address so they're stable per property. */
export interface RoofMeasurements {
  totalAreaSqFt: number
  squares: number
  facets: number
  ridgesFt: number
  hipsFt: number
  valleysFt: number
  eavesFt: number
  rakesFt: number
  predominantPitch: string
}

export function deriveMeasurements(meta: ReportMeta): RoofMeasurements {
  const rand = seededRandom(`${meta.address}|${meta.postalCode}|${meta.reportId}`)
  const totalAreaSqFt = Math.round(1400 + rand() * 2600)
  const squares = Math.round((totalAreaSqFt / 100) * 10) / 10
  const facets = 4 + Math.floor(rand() * 8)
  const ridgesFt = Math.round(30 + rand() * 90)
  const hipsFt = Math.round(rand() * 70)
  const valleysFt = Math.round(rand() * 60)
  const eavesFt = Math.round(80 + rand() * 120)
  const rakesFt = Math.round(60 + rand() * 110)
  const pitches = ["4/12", "5/12", "6/12", "7/12", "8/12", "9/12"]
  const predominantPitch = pitches[Math.floor(rand() * pitches.length)]
  return { totalAreaSqFt, squares, facets, ridgesFt, hipsFt, valleysFt, eavesFt, rakesFt, predominantPitch }
}

const BRAND = rgb(0.12, 0.32, 0.28)
const INK = rgb(0.1, 0.12, 0.12)
const MUTED = rgb(0.45, 0.48, 0.48)
const LINE = rgb(0.85, 0.87, 0.86)

function drawHeader(page: PDFPage, bold: PDFFont, font: PDFFont, title: string, meta: ReportMeta) {
  const { width, height } = page.getSize()
  page.drawRectangle({ x: 0, y: height - 90, width, height: 90, color: BRAND })
  page.drawText("RoofPitch", { x: 48, y: height - 46, size: 20, font: bold, color: rgb(1, 1, 1) })
  page.drawText(title, { x: 48, y: height - 68, size: 11, font, color: rgb(0.85, 0.92, 0.9) })
  page.drawText(`Report #${meta.reportId}`, {
    x: width - 48 - bold.widthOfTextAtSize(`Report #${meta.reportId}`, 10),
    y: height - 46,
    size: 10,
    font: bold,
    color: rgb(1, 1, 1),
  })
  const dateStr = new Date().toLocaleDateString("en-CA")
  page.drawText(dateStr, {
    x: width - 48 - font.widthOfTextAtSize(dateStr, 10),
    y: height - 62,
    size: 10,
    font,
    color: rgb(0.85, 0.92, 0.9),
  })
}

function drawFooter(page: PDFPage, font: PDFFont) {
  const { width } = page.getSize()
  const note = "Generated by RoofPitch demo measurement service. For illustration only."
  page.drawText(note, { x: 48, y: 40, size: 8, font, color: MUTED })
  page.drawLine({ start: { x: 48, y: 56 }, end: { x: width - 48, y: 56 }, thickness: 0.5, color: LINE })
}

/** A labeled value row used for the measurement summary. */
function drawRow(page: PDFPage, bold: PDFFont, font: PDFFont, y: number, label: string, value: string) {
  const { width } = page.getSize()
  page.drawText(label, { x: 48, y, size: 11, font, color: INK })
  page.drawText(value, {
    x: width - 48 - bold.widthOfTextAtSize(value, 11),
    y,
    size: 11,
    font: bold,
    color: INK,
  })
  page.drawLine({ start: { x: 48, y: y - 8 }, end: { x: width - 48, y: y - 8 }, thickness: 0.5, color: LINE })
}

/** Generates the roof measurement report PDF. Returns raw bytes. */
export async function generateReportPdf(meta: ReportMeta): Promise<Uint8Array> {
  const m = deriveMeasurements(meta)
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const page = doc.addPage([612, 792]) // US Letter
  const { height } = page.getSize()

  drawHeader(page, bold, font, "Roof Measurement Report", meta)

  let y = height - 130
  page.drawText("Property", { x: 48, y, size: 13, font: bold, color: BRAND })
  y -= 20
  page.drawText(meta.address, { x: 48, y, size: 11, font, color: INK })
  y -= 16
  if (meta.postalCode) {
    page.drawText(`Postal code: ${meta.postalCode}`, { x: 48, y, size: 11, font, color: MUTED })
    y -= 16
  }
  if (meta.product) {
    const sel = `Selected: ${meta.product}${meta.color ? ` · ${meta.color}` : ""}`
    page.drawText(sel, { x: 48, y, size: 11, font, color: MUTED })
    y -= 16
  }

  y -= 18
  page.drawText("Measurement Summary", { x: 48, y, size: 13, font: bold, color: BRAND })
  y -= 26

  drawRow(page, bold, font, y, "Total roof area", `${m.totalAreaSqFt.toLocaleString()} sq ft`)
  y -= 28
  drawRow(page, bold, font, y, "Roofing squares", `${m.squares}`)
  y -= 28
  drawRow(page, bold, font, y, "Number of facets", `${m.facets}`)
  y -= 28
  drawRow(page, bold, font, y, "Predominant pitch", m.predominantPitch)
  y -= 28
  drawRow(page, bold, font, y, "Ridges", `${m.ridgesFt} ft`)
  y -= 28
  drawRow(page, bold, font, y, "Hips", `${m.hipsFt} ft`)
  y -= 28
  drawRow(page, bold, font, y, "Valleys", `${m.valleysFt} ft`)
  y -= 28
  drawRow(page, bold, font, y, "Eaves", `${m.eavesFt} ft`)
  y -= 28
  drawRow(page, bold, font, y, "Rakes", `${m.rakesFt} ft`)

  drawFooter(page, font)
  return doc.save()
}

/** Generates the materials list PDF (waste factor + line items). Returns bytes. */
export async function generateMaterialsPdf(meta: ReportMeta): Promise<Uint8Array> {
  const m = deriveMeasurements(meta)
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const page = doc.addPage([612, 792])
  const { width, height } = page.getSize()

  drawHeader(page, bold, font, "Estimated Materials List", meta)

  let y = height - 130
  page.drawText("Property", { x: 48, y, size: 13, font: bold, color: BRAND })
  y -= 20
  page.drawText(meta.address, { x: 48, y, size: 11, font, color: INK })
  y -= 30

  const wasteFactor = 0.1
  const squaresWithWaste = Math.ceil(m.squares * (1 + wasteFactor))
  const bundles = squaresWithWaste * 3 // 3 bundles per square
  const underlaymentRolls = Math.ceil((m.totalAreaSqFt * (1 + wasteFactor)) / 400)
  const dripEdge = Math.ceil((m.eavesFt + m.rakesFt) / 10)
  const ridgeCap = Math.ceil((m.ridgesFt + m.hipsFt) / 20)
  const valleyRolls = Math.ceil(m.valleysFt / 50)
  const nailsLbs = Math.ceil(squaresWithWaste * 2.5)

  page.drawText(`Materials Estimate (incl. ${Math.round(wasteFactor * 100)}% waste)`, {
    x: 48,
    y,
    size: 13,
    font: bold,
    color: BRAND,
  })
  y -= 12

  // Table header
  y -= 18
  page.drawText("Item", { x: 48, y, size: 10, font: bold, color: MUTED })
  page.drawText("Quantity", { x: width - 48 - bold.widthOfTextAtSize("Quantity", 10), y, size: 10, font: bold, color: MUTED })
  page.drawLine({ start: { x: 48, y: y - 6 }, end: { x: width - 48, y: y - 6 }, thickness: 0.75, color: LINE })
  y -= 24

  const items: Array<[string, string]> = [
    [`Shingle bundles (${meta.product ?? "architectural"}${meta.color ? `, ${meta.color}` : ""})`, `${bundles} bundles`],
    ["Underlayment", `${underlaymentRolls} rolls`],
    ["Drip edge", `${dripEdge} pcs (10 ft)`],
    ["Ridge cap shingles", `${ridgeCap} bundles`],
    ["Valley flashing", `${valleyRolls} rolls`],
    ["Roofing nails", `${nailsLbs} lbs`],
    ["Squares (with waste)", `${squaresWithWaste}`],
  ]
  for (const [label, value] of items) {
    page.drawText(label, { x: 48, y, size: 11, font, color: INK })
    page.drawText(value, { x: width - 48 - bold.widthOfTextAtSize(value, 11), y, size: 11, font: bold, color: INK })
    page.drawLine({ start: { x: 48, y: y - 8 }, end: { x: width - 48, y: y - 8 }, thickness: 0.5, color: LINE })
    y -= 28
  }

  drawFooter(page, font)
  return doc.save()
}
